baseURL = "//blog.yech.xyz/"
languageCode = "en-us"
title = "Chang's blog"
copyright = "2020 by Ye Chang"
disableKinds = ["section"]
theme = "diary"
googleAnalytics = "UA-71962122-1"
enableGitInfo = true

[params]
    subtitle = "learn and share..."
    favicon = "favicon-96x96.png"
    disableToC = false
    enableGitalk = true

[params.gitalk]
    owner = "gitalk-bot"
    repo = "blog.yech.xyz"
    client_id = "34a558922e45dfca085b"
    client_secret = "af844fa274bad7885b0d3b2a20cb9bdb0fd62ca1"

[taxonomies]
    tag = "tags"
    category = "categories"

[[menu.main]]
    url = "/categories"
    name = "Categories"
    weight = 1

[[menu.main]]
    url = "/tags"
    name = "Tags"
    weight = 2

[markup.goldmark.renderer]
    unsafe = true

[markup.goldmark.extensions]
    footnote = true
