baseURL = "https://blog.yech.xyz/"
languageCode = "en-us"
title = "Chang's blog"
copyright = "2024 by Ye Chang"
disableKinds = ["section"]
theme = "diary"
googleAnalytics = "UA-71962122-1"
enableGitInfo = true

[params]
    subtitle = "learn and share..."
    favicon = "favicon-96x96.png"
    disableToC = false
    enableGitalk = false

[taxonomies]
    tag = "tags"
    category = "categories"

[[menu.main]]
    url = "/categories"
    name = "Categories"
    weight = 1

[[menu.main]]
    url = "/tags"
    name = "Tags"
    weight = 2

[markup.goldmark.renderer]
    unsafe = true

[markup.goldmark.extensions]
    footnote = true
